
language: python
python:
- '3.6'
dist: bionic

before_install:
- sudo apt-get update
- sudo apt-get install -y portaudio19-dev=19.6.0-1

install:
- pip install -r requirements.txt

script:
- pytest

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  server: https://testpypi.python.org/pypi  # Test PyPi upload.
  user: __token__
  password:
    secure: KG5J//NE6CkmHu/gR6+glPsUztIrG8+qe3zLAKdn3yPmqS/ekZDwMynlMOI/gYi3reCOy274NNrhShkfUb/mx0suIMS1jqZB0LY0eWrLkZKekqXHV/3MYJIdCO8AxXzVZPoN8RGZjoa7JqrIbeaVCw9ggoukLbKYs1VQWij10HCOnYH90yg4DMM6YM7xcsosP38QdXR3c+V8ZsMKAgVTB8grslj3xRxwkiwGmsDfsGEqFJAuxKZN8fRDkS8HbdLh+ER8XjhXAy941cc4WzG/uXBpOQpmsdclkT7NQ92qAxiVRTsOt6QftYDo0ZiW8CaLC8HV++l+UF7NBkyVPeQxU0G+vdLG9GpPjG2lKjI5JAfXWoJVDXx7kDzfFnfdXJY1ec94lbqV/XfU8LPEKd3C84NLGi6jme1/cgGI818zbCBcldZycJLS6VLi2k9Ncfb9D8TaUF2e7/srhSntCwFWsEVQQ844FmJwXhzFCva3DykaDM9GW+F8rCGR/QScEAfkRfugGFMk9mNjh+pgpeM6Yg0MS089PdMVU9Zl/OTCCOJM+EhfVtAeMhlMUIwBg4VjVVCsmEf95nxkmoESeE5Dzua3mHiP5XvZGUrqAaKSUjN0u7oCeTeHnR6GN441c2XihyrVffff6dmGc5NYOsTpRVxtByQ9/rcc6VaM3bGxTf0=
  on:
    tags: true

